name: CD - Build, Push and Update K8s Manifest

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  IMAGE_NAME: goldenowl-devops-internship-challenge
  MANIFEST_BRANCH: k8s-manifests
  MANIFEST_FILE: k8s-infrastructure/apps/goldenowl-devops-internship-challenge/stack.yaml
  DEPLOYMENT_NAME: goldenowl-devops-internship-challenge-deployment

jobs:
  deploy:
    name: Build, Push and Update K8s
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Git tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Checkout k8s-manifests branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.MANIFEST_BRANCH }}
          path: k8s-infra

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update application image in manifest
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
        run: |
          cd k8s-infra
          yq -i '
            (. | select(.kind == "Deployment" and .metadata.name == strenv(DEPLOYMENT_NAME)) | .spec.template.spec.containers[0].image) = strenv(IMAGE)
          ' "${{ env.MANIFEST_FILE }}"

      - name: Commit and push manifest
        run: |
          cd k8s-infra
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "${{ env.MANIFEST_FILE }}"
          git commit -m "chore: update image to ${{ env.TAG_NAME }}" || echo "No changes to commit"
          git push origin HEAD:${{ env.MANIFEST_BRANCH }}
