name: CI - Test Application

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  test:
    name: Run Code Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' 
          cache: 'npm'
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        working-directory: ./src
        run: npm ci

      - name: Run tests
        working-directory: ./src
        run: npm test 
